version: '3'
services:
  microservice:
    container_name: api_rest
    image: express_api:latest
    ports:
      - 3000:3000

  microservice_db:
    container_name: api_db
    build: container/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./data/mysql:/var/lib/mysql

networks:
  default:
    external:
      name: $DOCKER_NETWORK
